name: Build, test and report.

on:
  push:
    branches:
      - '*'
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          always-auth: true
          registry-url: https://registry.npmjs.org/
          scope: '@agilxp'
      - run: yarn
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
